// Subquestion types
export const IS_AFTER_BE_SUBQUESTION = 'IS_AFTER_BE_SUBQUESTION';
export const COMPLEMENT_SUBQUESTION = 'COMPLEMENT_SUBQUESTION';

// Current question modes
export const ANSWERING_MODE = 'ANSWERING_MODE';
export const CHECKED_MODE = 'CHECKED_MODE';

// Action types
export const BUTTON_CLICKED = 'BUTTON_CLICKED';
export const CHECK_ANSWERS = 'CHECK_ANSWERS';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const FETCH_QUIZ = 'FETCH_QUIZ';
export const SKIP_QUESTION = 'SKIP_QUESTION';
export const SET_PROGRESS_STATUS = 'SET_PROGRESS_STATUS';
export const ADD_SUCCESS_TO_PROGRESS = 'ADD_SUCCESS_TO_PROGRESS';
export const ADD_WRONG_TO_PROGRESS = 'ADD_WRONG_TO_PROGRESS';
export const SPLIT_QUESTIONS = 'SPLIT_QUESTIONS';
export const SHOW_RESULT = 'SHOW_RESULT';